version: '3.4'

services:
  data-api:
    build: ./data-api/
    volumes:
      - ./data-api:/code
    ports:
      - 8080:8080
    env_file: .env

  # web:
  #   build:
  #     context: ./
  #     target: runner
  #   volumes:
  #     - .nex/:/app
  #   command: yarn dev
  #   ports:
  #     - '3000:3000'
  #   # extra_hosts:
  #   #   - 'host.docker.internal:host-gateway'
  #   environment:
  #     NODE_ENV: development

  db:
    image: postgres:14.7
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
