version: '3.4'

services:
  data-api:
    build: ./data-api/
    volumes:
      - ./data-api:/code
    ports:
      - 8080:8080
    env_file: .env

  db:
    image: postgres:14.7
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
