version: '3.4'

services:
  db:
    image: postgres:14.7
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env

  data-api:
    build: ./data-api/
    volumes:
      - ./data-api:/code
      - ./tmp/dataset_cache:/root/.cache/huggingface/datasets/
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - db

  web:
    build:
      context: ./next 
      dockerfile: Dockerfile
      args:
        EXTERNAL_API: ${NEXT_PUBLIC_API_URL}
    image: web-image:latest
    volumes:
      - ./next/src:/app/src
    command: sh -c  "yarn migrate && yarn start"
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - data-api
      