FROM node:18-slim AS deps
# RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock ./
RUN  yarn --frozen-lockfile

FROM node:18-slim AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules

COPY . .
COPY start.sh /start.sh
RUN chmod +x /start.sh

ENV NEXT_TELEMETRY_DISABLED 1

# Expose port
EXPOSE 3000

# Start the application
CMD [ "/bin/sh", "/start.sh" ]
